### PR TITLE
Friendshipv2

### PR DESCRIPTION
**Pull request by vidhishweta01**
This repo includes intial code for social media app with basic styling. Its purpose is to be a starting point for Microverse students.
generated invitation model, added invitaion methods in Invitation.rb, changed view, added controller for invitation model, added controller for user. 
added mutual friends method in user_helper

### CODE REVIEW

**Review by smcommits — CHANGES_REQUESTED** [review]
# Status: Changes Required 

## Hello, @vidhishweta01! You are doing a great job. The application is outstanding. Excellent work. To make this project even better, we need to address some issues that are the basic requirements of this milestone. 

## Required Changes 

- [ ]  **When friendship is confirmed, create an additional row with reversed friendship row.**

Currently, you are confirming friendship by updating the status of the existing Invitation. As per the requirement, when a request is confirmed, you should create a reversed row of that invitation. 

What does this mean? 

Suppose, A has sent a friend request to B. The Invitations table will contain a row where A is the User and B is the friend. Now, as soon as B accepts the friendship, your program should create a mirrored row where B will be the User and A will be the friend. 

To understand the concept better, please refer to [this article](https://explainextended.com/2009/03/07/selecting-friends/)

#### Please note, while you are changing how invitations and friendships are stored, you should accordingly modify the User model to make use of efficient queries and methods related to friendships. 

<hr>

- [ ] **Please add unit and integration testing for your application.** 

You can Rspec Rails. 
To perform integration testing, you can Capybara. 
To test the associations, you can use something like the gem "Shoulda Matchers"


# 

#### Please requested another review from your dashboard once you are ready. 

#### Please reach out to me on Slack if you need any assistance or believe I have overlooked something and made an unfair request.

**Comment by vidhishweta01** [comment]
As per the requirement model behaves, SQL best practice have been followed

Screenshot from 2021-05-11 16-43-58

Screenshot from 2021-05-11 16-47-02

Screenshot from 2021-05-11 16-48-07

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Shweta Srivastava** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a couple of details to improve before you can go ahead:

- [ ] Add capybara to your Gemfile
- [ ] In your invitation model, you should have a method that creates a second row (with user_id and friend_id values inverted) for the friendship after it is confirmed.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by vidhishweta01** [comment]
Hi, As per requirement there are two articles which mention that how to remove reverse pairing in model and if I add the feature which is asked in code review  it will violate Domain-Key Normal Form  and bring inconsistency and redundancy in the model and in this project there is a method which ensure the all the friends which are made via sending friend request as well as via accepting friend request are considered as user's friend so inverted row is not required.
 
Screenshot from 2021-05-11 16-48-07

Screenshot from 2021-05-11 16-43-58

**Review by BrianSammit — APPROVED** [review]
STATUS: APROVED :green_circle: 
-------------
Hello @vidhishweta01 Great job Working on the required changes. :+1: :1st_place_medal: 
--------------
Now you can merge this branch :muscle: 
HAPPY CODING!!!

**Pull request merged**
